name: Deploy to PythonAnywhere
on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PYTHONANYWHERE_HOST }}
          username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          password: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
          script: |
            cd /home/${{ secrets.PYTHONANYWHERE_USERNAME }}/YOUR_REPO_NAME
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            touch /var/www/${{ secrets.PYTHONANYWHERE_USERNAME }}_pythonanywhere_com_wsgi.py
